name: cupcake-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pillow
  - opencv
  - scikit-image
  - scikit-learn
  - tqdm
  - psutil
  - exifread
  - pip
  - libraw  # Added LibRaw from conda-forge
  - pip:
    - tensorflow==2.12.0
    - imagehash>=4.2.0

# Note: rawpy has been removed in favor of the built-in RAW handling system
# and LibRaw installed via conda