name: cupcake-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - opencv
  - tensorflow
  - scikit-image
  - scikit-learn
  - tqdm
  - psutil
  - pip
  - pip:
    - rawpy>=0.17.0
    - exifread>=2.3.2
    - imagehash>=4.2.0